verbose: false
reporting:
    reports:
        - lcov
        - json
        - text
check:
    global:
        statements: 50
        branches: 50
    each:
        statements: 50
        branches: 50
